### ISSUE TITLE
Jackett

### ISSUE THREAD

**Issue by tomaso0** [danamag/stremio-addons-list#278]
### Addon Manifest URL

https://jackett-v79c.onrender.com/manifest.json

### Addon Description

watch movies and series

### Language of Content

None

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [ ] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by enko2974** [comment]
Can you add real debrid support?thank you

**Comment by tsaridas** [comment]
It would be a thoughtful and inclusive approach to consider renaming the addon in order to ensure that people from all backgrounds, regardless of race, color, nationality, or religion, can enjoy it without encountering any potentially controversial or uncomfortable topics.

**Comment by tomaso0** [comment]
> It would be a thoughtful and inclusive approach to consider renaming the addon in order to ensure that people from all backgrounds, regardless of race, color, nationality, or religion, can enjoy it without encountering any potentially controversial or uncomfortable topics.

I appreciate your great work thank you. But I don't think anyone should be offended, Israel is a great country.

**Comment by lothar-cell** [comment]
I appreciate that you are bringing an installable Jackett addon to the community, but you really should not doing this with bringing politics with it. And not because you are right or wrong, but because I don't want to see politics at the place where I go to forget about it. It's just invasive and not done in a good taste. When I go and watch Nightmare before Christmas, I don't want to think about loving any country, not even mine, because it's not the right time for it.

Please rename it to just Jackett. 
Also, it would be great if the sources were organised properly by resolution/seeders. Real-Debrid would be nice too:)

**Comment by tomaso0** [comment]
Addon name updated to Jackett

**Comment by lothar-cell** [comment]
Thank you!

**Comment by Doctor2023** [comment]
This addon status offine the jackett addon that happened with the jackett addon in stremio app

**Comment by GitGud117** [comment]
Free Palestine.

**Comment by lothar-cell** [comment]
The add-on is down.
