### ISSUE TITLE
Cinestream by dexter21767

### ISSUE THREAD

**Issue by dexter21767** [danamag/stremio-addons-list#63]
### Addon Manifest URL

https://2ecbbd610840-cinestream.baby-beamup.club/manifest.json

### Addon Description

fast stream over https with multiple subtitles directly from cinemeta, by Dexter21767

### Choose Labels

- [ ] anime
- [ ] asian drama
- [ ] bollywood
- [ ] cartoons
- [ ] debrid support
- [X] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [X] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [ ] torrents
- [X] tv shows
- [ ] video games

**Comment by GKid94** [comment]
Doesn't show Serbian subtitles

**Comment by axl666ve** [comment]
the add-on works fine with the FlixHQ server but in a totally unpredictable way it usually crashes and automatically switches to "Viewasian" and "Dramacool" servers (usually on weekends), which redirect to Asian dramas no matter what one chooses. I guess this happens on weekends because of the increased number of users. Please fix this, "Viewasian" and "Dramacool" are totally worthless, the only server that works perfectly is FlixHQ and it is the one that should remain as the default server.

**Comment by Musyoxxx** [comment]
This is excellent. Thank you. Enjoying it so far.

**Comment by hsp1020** [comment]
If you want to watch Asian dramas, the connection is unstable (and sometimes the results are not coming out at all)

**Comment by hsp1020** [comment]
Thank you for your hard work.
When I try to watch an Korean drama, the connection is unstable.
Sometimes it is in FilxHQ, Dramacool, and ViewAsian, but it does not appear in the search results for cinestream.

**Comment by Lookattheskyl** [comment]
The addon works fine. There is no option expect this addon for http streaming.

**Comment by Musyoxxx** [comment]
Tried it last week, as I was reconsidering my alldebrid subscription. It
works extremely well. I have some regrets about not sticking with it, maybe
i'll give this a full month next time.
