### ISSUE TITLE
One Pace Addon

### ISSUE THREAD

**Issue by fedew04** [danamag/stremio-addons-list#707]
### Addon Manifest URL

https://raw.githubusercontent.com/fedew04/OnePaceStremio/refs/heads/main/manifest.json

### Addon Description

One Pace is a fan project that recuts the One Piece anime in an endeavor to bring it more in line with the pacing of the original manga by Eiichiro Oda. The team accomplishes this by removing filler scenes not present in the source material. This process requires meticulous editing and quality control to ensure seamless music and transitions.

This is the One Pace addon for Stremio (https://onepace.net/). Go to Discover -> Series -> One Pace to watch. Recommended: Set your default subtitle size to 160% before watching.

### Language of Content

Multilingual (Default)

### Choose Labels

- [X] anime
- [ ] asian drama
- [ ] bollywood
- [X] cartoons
- [ ] debrid support
- [ ] http streams
- [ ] live tv
- [ ] metadata
- [ ] misc
- [ ] movies
- [ ] music
- [ ] nsfw
- [ ] podcasts
- [ ] radios
- [X] subtitles
- [X] torrents
- [X] tv shows
- [ ] video games

**Comment by sleeyax** [comment]
@fedew04 I  approved your addon but because your `manifest.json` is pointing to a file on GitHub users won't be able to install the addon. Therefore our verification bot closed your issue automatically.

If you're looking for a free and easy hosting solution you can use https://github.com/Stremio/stremio-beamup. The manifest URL you need to submit should look something like this: `https://b89262c192b0-your-addon-name.baby-beamup.club/manifest.json`.

Once your addon is online and reachable, try submitting it here again.
